### ISSUE TITLE
error: Could not download: SSL support is not available

### ISSUE THREAD

**Issue by hugosenari** [nix-community/flake-nimble#13]
Hi,

When running update command:

```bash
nix run .#package-updater
```

It shows the following error:
```text
/nix/store/07iwgh2zr4q8ywby2wpj8fwbrcfcq723-nimble-src-0.11.0/src/nimblepkg/packageinfo.nim(228) fetchList
Error: unhandled exception: Refresh failed
Could not download: SSL support is not available. Cannot connect over SSL. Compile with -d:ssl to enable. [NimbleError]
```

@bandithedoge PR (#12) solves this [adding](https://github.com/nix-community/flake-nimble/pull/12/files#diff-f838dd30f7aebd72dc21b473cc73695d1bc6c7eef3a3b32217ee163564f866b9R98)  `-d:ssl` flag

**Comment by ehmry** [comment]
Yes, fixed at c26cce02f86d8d7b656318a1f61f7d2e5d326108.
