### ISSUE TITLE
"error: flake has an unsupported attribute 'edition'"

### ISSUE THREAD

**Issue by akavel** [nix-community/flake-nimble#2]
I'm on NixOS (20.09); I installed flakes support by adding `nix.package = pkgs.nixUnstable` and `nix.extraOptions = ''experimental-features = nix-command flakes'';` in my `/etc/nixos/configuration.nix`. When I try to run a flake from "nimble" repository, I'm getting an error:

```text
$ nix run nimble#nimterop -- --help
warning: unknown setting 'extra-sandbox-paths'
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------- nix
flake 'github:nix-community/flake-nimble/22e4e490b5d5ad15e78c9225022d0dc43d65af8a' has an unsupported attribute 'edition', at /nix/store/vx4zih0ainkmghglpgfh236w78mp1m3g-source/flake.nix:2:3
```

I tried also with: `nix.package = pkgs.nixFlakes` and `sudo nixos-rebuild switch`, but the error seems to be still exactly the same.

I [was advised at the NixOS discourse](https://discourse.nixos.org/t/error-flake-has-an-unsupported-attribute-edition/10329), that:

> `edition` used to be a (required?) attribute for flakes, but was since then removed. Some older flakes still have this attribute. It is best to file an issue or PR in the flake-nimble repo to ask that the `edition` attribute is removed from `flake.nix`.

Would you possibly care to try and remove the `edition` attribute? TIA!

**Comment by ehmry** [comment]
I believe that if the edition where updated the packages in the flake would still be broken, and my patience for dealing with the Nim tools is worn too thin to try to fix any of it.

**Comment by akavel** [comment]
Oh!... could you possibly fancy sharing some hints as to what else was/is broken, and what troubles you especially remember having with the packages? I would agree that I find the tooling situation around Nim less than ideal; but personally I find the language just plainly really, really, really fun - and I thought recently that Nix could maybe help me mitigate the tooling situation (esp. nimble's lack of library pinning mechanism), esp. with flakes :) so I was really blown away to find this repository that you created! As such, I have some "scratch my own itch" (i.e. kinda the best one!) motivation to try and make this at least somewhat usable and play a bit with it maybe :) [though I won't even try to make any promises of continued maintenance, as I have awful track record in this area :( ] so any hints at what kind of trouble I should expect would be useful and highly appreciated to help me evaluate this idea and possibly set my expectations :) any extra random bits of vague ideas how you thought about maybe resolving some of those "some day" are absolutely optional yet totally welcome as well :D

**Comment by ehmry** [comment]
I've updated the flake to remove the edition and updated the compiler. The [utility](https://github.com/nix-community/flake-nimble/blob/c9226481c60d6b4365f15cd9d155a534e2f4ae31/src/nix_from_nimble.nim) for generating the package metadata probably needs a rewrite.

Going forward, I would try to minimize any coupling with the Nimble and try to drive the Nim compiler directly. To be clear, I'm convinced that Nimble is redundant and unsafe and should be killed off by Nix.

**Comment by akavel** [comment]
Cool, thanks! And thanks for letting me know that you're open to modifying/rewriting nimbleHelper, I wasn't sure what's your stance towards it. Still, for the time being, I've actually added a few small quality-of-life improvements to it in the meantime, I'll open a separate PR for them in case you wouldn't mind considering them for merge.

As to Nimble being dangerous, I think I probably understand what you mean; that said, I suspect it may take time and patience. Nix, great as it is, isn't exactly a trivial nor lightweight solution, so I don't suspect it to be a quick & easy sell for any community, including the Nim one... And appreciating Nix requires quite a lot of maturity - to be able to even recognize and acknowledge existence of the problems it's fixing. And as far as I understand the state of the Nim community with regards to package management, Nimble is I think actually a relatively recent development to start with, introducing at least some unification in the ecosystem; I believe before that, there was kinda "to each their own", a number of competing incompatible standards... So as much as Nimble and its approach has warts and issues, I'm also glad that the tool you wrote *can actually be written at all* now...

And by the way, as a side note, as much as I totally recognize and appreciate Nix's benefits, I don't see its ecosystem as perfect at this point in time either... In particular, related to the topic of libraries management that is of concern to us here, I'd really wish that maintainers of different languages' library systems would come together and try to agree on a unified mechanism, and learn from each others' experiences... I'm not sure if the current state of things in nixpkgs is more due to [the Lisp Curse](http://winestockwebdesign.com/Essays/Lisp_Curse.html), or an example of [the Lava Layers antipattern](https://mikehadlow.blogspot.com/2014/12/the-lava-layer-anti-pattern.html), but between vim plugins, node.js packages, Python, LuaRocks, Go language, and whatever else I look at, I cringe and sigh deeply every time I need to seem to have to learn each new ecosystem's way of doing things more or less from scratch... Not that there aren't things I cringe about in Nim or Nimble, far from it ;) It's just that in the end, I see both Nix and Nim as great and valuable tools, where in case of both, the fun & value I get from them seems to noticeably outweigh the trouble they give me :) So in particular, huge thanks to you for all your contributions in Nix & Nim!
