### ISSUE TITLE
Add Example

### ISSUE THREAD

**Issue by floscr** [nix-community/flake-nimble#5]
I would very much like to use this project, but I'm having a hard time figuring out how to glue it together.
Could it be possible to add a simple example that builds a nim binary with a package from flake-nimble?
Would be much appreciated :bow:

**Comment by ehmry** [comment]
I don't think anyone knows yet how this should be used, you can build a few simple binaries, but there is a pervasive problem here that we don't know what the non-Nim dependencies are (such as pkg-config or SDL).

If you want an example of how to refer to Nim packages when building a Nix package, I have this: https://git.sr.ht/~ehmry/upload_bot/tree/master/item/flake.nix

**Comment by floscr** [comment]
Okay thank you that helps :slightly_smiling_face:
